global:
  resolve_timeout: 5m

route:
  receiver: 'servicenow-receiver-1'

receivers:
  - name: 'servicenow-receiver-1'
    webhook_configs:
      - url: "http://10.83.173.61:9877/webhook"
        send_resolved: true
