global:
  resolve_timeout: 5m

route:
  receiver: 'servicenow-receiver-1'

receivers:
  - name: 'servicenow-receiver-1'
    webhook_configs:
      - url: "http://localhost:9877/webhook"
        send_resolved: true
        http_config: global.http_config