version: "3"

services:
  alert-manager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ${PWD}/alertmanager/alertmanager.yml:/alertmanager.yml
    command:
      - '--log.level=debug'
      - '--config.file=/alertmanager.yml'
