version: "3"

services:
  alert-manager:
    container_name: alertmanager
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ${PWD}/alertmanager/alertmanager.yml:/alertmanager/alertmanager.yml
    command:
      - '--log.level=debug'
      - '--config.file=/alertmanager/alertmanager.yml'
