version: '3'

services:

  eemapi:
    build: .
    container_name: eemapi
    image: eemapi
    ports:
      - "9000:9000"

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
      - "6831:6831/udp"

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - $PWD/prometheus/prometheus.yml:/prometheus/prometheus.yml
      - $PWD/alertmanager/alert.rules:/alertmanager/alert.rules
    command:
      - '--config.file=/prometheus/prometheus.yml'

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"

  grafana:
    container_name: grafana
    image: grafana/grafana:5.4.3
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret

  alert-manager:
    container_name: alertmanager
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ${PWD}/alertmanager/alertmanager.yml:/alertmanager/alertmanager.yml
    command:
      - '--log.level=debug'
      - '--config.file=/alertmanager/alertmanager.yml'
    depends_on:
      - prometheus
