version: "3"

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - $PWD/prometheus/prometheus.yml:/prometheus/prometheus.yml
      - $PWD/alertmanager/alert.rules:/alertmanager/alert.rules
    command:
      - '--config.file=/prometheus/prometheus.yml'