global:
  scrape_interval: 10s
  external_labels:
    monitor: 'eemapi-monitor'

scrape_configs:
  - job_name: 'spring_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ["{{HOST_IP}}:9000"]

  - job_name: 'node-exporter'
    static_configs:
      - targets: ["{{HOST_IP}}:9100"]

rule_files:
  - "/alertmanager/alert.rules"


alerting:
  alertmanagers:
    - static_configs:
        - targets: ["{{HOST_IP}}:9093"]
