version: "3"

services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_lib:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
