version: "3"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - $PWD/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - $PWD/alertmanager/alert.rules:/etc/alertmanager/alert.rules
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
